apiVersion: v2
name: unifi-network-application
description: A Helm chart for Kubernetes
type: application
version: "0.4.3"
appVersion: "10.0.162"
maintainers:
  - name: Balazs Petrikovics
    email: bpetrikovics@gmail.com
  - name: Gabor Pichner
    email: 95gabor@gmail.com
